export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const ADD_PRODUCT = 'ADD_PRODUCT';

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
